# Generated by Django 5.1.2 on 2025-01-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_description_products_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Описание'),
        ),
    ]
