# Generated by Django 5.1.6 on 2025-02-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_requieres_delievery_order_requires_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='requires_delivery',
            new_name='requieres_delievery',
        ),
    ]
